window.page_patterns = [
  {
    "pattern": "^\\/$",
    "negativepattern": "",
    "etapa": "AUDIENCIA",
    "fluxo": "",
    "tipo": "HOME",
    "produto": "HOME",
    "pagina": "HOME",
    "segmento": "NA",
    "canal": "",
    "origem": "passo201_detalheoferta"
  },
  {
    "pattern": "^/fixo\\/?$",
    "negativepattern": "",
    "etapa": "AUDIENCIA",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "FIXO",
    "pagina": "P FIXO",
    "segmento": "RESIDENCIAL",
    "canal": "",
    "origem": "passo201_detalheoferta"
  },
  {
    "pattern": "^/internet\\/?$",
    "negativepattern": "",
    "etapa": "AUDIENCIA",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "BANDA LARGA",
    "pagina": "P BANDA LARGA",
    "segmento": "RESIDENCIAL",
    "canal": "",
    "origem": "passo201_detalheoferta"
  },
  {
    "pattern": "^\\/celular(\\/|\\/#!)controle\\/?$",
    "negativepattern": "",
    "etapa": "AUDIENCIA",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "CONTROLE",
    "pagina": "P CONTROLE",
    "segmento": "MOBILIDADE",
    "canal": "",
    "origem": "passo201_detalheoferta"
  },
  {
    "pattern": "^\\/celular(\\/|\\/#!)pos-pago\\/?$",
    "negativepattern": "",
    "etapa": "AUDIENCIA",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO",
    "segmento": "MOBILIDADE",
    "canal": "",
    "origem": "passo201_detalheoferta"
  },
  {
    "pattern": "^/tv-hd\\/?$",
    "negativepattern": "",
    "etapa": "AUDIENCIA",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "TV",
    "pagina": "P TV",
    "segmento": "RESIDENCIAL",
    "canal": "",
    "origem": "passo201_detalheoferta"
  },
  {
    "pattern": "^\\/combo\\/?$",
    "negativepattern": "",
    "etapa": "AUDIENCIA",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "COMBO",
    "pagina": "P COMBO",
    "segmento": "RESIDENCIAL",
    "canal": "",
    "origem": "passo201_detalheoferta"
  },
  {
    "pattern": "^/combo/(oi-total)?(#!)?-residencial\\/?$",
    "negativepattern": "",
    "etapa": "AUDIENCIA",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "COMBO RESIDENCIAL",
    "pagina": "P COMBO RESIDENCIAL",
    "segmento": "RESIDENCIAL",
    "canal": "",
    "origem": "passo201_detalheoferta"
  },
  {
    "pattern": "^/combo/(oi-total)?(#!)?-(completo|solucao-completa)\\/?$",
    "negativepattern": "",
    "etapa": "AUDIENCIA",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "COMBO COMPLETO",
    "pagina": "P COMBO COMPLETO",
    "segmento": "RESIDENCIAL",
    "canal": "",
    "origem": "passo201_detalheoferta"
  },
  {
    "pattern": "^/combo/(oi-total)?(#!)?-conectado\\/?$",
    "negativepattern": "",
    "etapa": "AUDIENCIA",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "COMBO CONECTADO",
    "pagina": "P COMBO CONECTADO",
    "segmento": "RESIDENCIAL",
    "canal": "",
    "origem": "passo201_detalheoferta"
  },
  {
    "pattern": "^/combo/oi-total-play\\/?$",
    "negativepattern": "",
    "etapa": "AUDIENCIA",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "COMBO OI PLAY",
    "pagina": "P COMBO OI PLAY",
    "segmento": "RESIDENCIAL",
    "canal": "",
    "origem": "passo201_detalheoferta"
  },
  {
    "pattern": "^/combo/oi-total-tv-fixo\\/?$",
    "negativepattern": "",
    "etapa": "AUDIENCIA",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "COMBO 2P TV",
    "pagina": "P COMBO 2P TV",
    "segmento": "RESIDENCIAL",
    "canal": "",
    "origem": "passo201_detalheoferta"
  },
  {
    "pattern": "^/15mega\\/?$",
    "negativepattern": "",
    "etapa": "AUDIENCIA",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "BANDA LARGA",
    "pagina": "LP 15MEGA",
    "segmento": "RESIDENCIAL",
    "canal": "",
    "origem": "passo201_detalheoferta"
  },
  {
    "pattern": "^/assine-tv\\/?$",
    "negativepattern": "",
    "etapa": "AUDIENCIA",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "TV",
    "pagina": "LP ASSINE TV",
    "segmento": "RESIDENCIAL",
    "canal": "",
    "origem": "passo201_detalheoferta"
  },
  {
    "pattern": "^/assine-combo\\/?$",
    "negativepattern": "",
    "etapa": "AUDIENCIA",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "COMBO",
    "pagina": "LP ASSINE COMBO",
    "segmento": "RESIDENCIAL",
    "canal": "",
    "origem": "passo201_detalheoferta"
  },
  {
    "pattern": "^/assine-pos\\/?$",
    "negativepattern": "",
    "etapa": "AUDIENCIA",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP ASSINE POS",
    "segmento": "MOBILIDADE",
    "canal": "",
    "origem": "passo201_detalheoferta"
  },
  {
    "pattern": "^/assine-controle\\/?$",
    "negativepattern": "",
    "etapa": "AUDIENCIA",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "CONTROLE",
    "pagina": "LP ASSINE CONTROLE",
    "segmento": "MOBILIDADE",
    "canal": "",
    "origem": "passo201_detalheoferta"
  },
  {
    "pattern": "^/assine-oi-controle\\/?$",
    "negativepattern": "",
    "etapa": "AUDIENCIA",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "CONTROLE",
    "pagina": "LP ASSINE OI CONTROLE",
    "segmento": "MOBILIDADE",
    "canal": "",
    "origem": "passo201_detalheoferta"
  },
  {
    "pattern": "^/migre-pra-controle\\/?$",
    "negativepattern": "",
    "etapa": "AUDIENCIA",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "CONTROLE",
    "pagina": "LP MIGRE CONTROLE",
    "segmento": "MOBILIDADE",
    "canal": "",
    "origem": "passo201_detalheoferta"
  },
  {
    "pattern": "^/migrar-controle\\/?$",
    "negativepattern": "",
    "etapa": "AUDIENCIA",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "CONTROLE",
    "pagina": "LP MIGRAR CONTROLE",
    "segmento": "MOBILIDADE",
    "canal": "",
    "origem": "passo201_detalheoferta"
  },
  {
    "pattern": "^/4g/?$",
    "negativepattern": "",
    "etapa": "AUDIENCIA",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP 4G",
    "segmento": "MOBILIDADE",
    "canal": "",
    "origem": "passo201_detalheoferta"
  },
  {
    "pattern": "^\\/celular\\/(#!)?pre-pago\\/?$",
    "negativepattern": "",
    "etapa": "AUDIENCIA",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "PRE-PAGO",
    "pagina": "P PRE-PAGO",
    "segmento": "MOBILIDADE",
    "canal": "",
    "origem": "passo201_detalheoferta"
  },
  {
    "pattern": "^/mais-controle\\/?$",
    "negativepattern": "",
    "etapa": "AUDIENCIA",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "CONTROLE",
    "pagina": "LP MAIS CONTROLE",
    "segmento": "MOBILIDADE",
    "canal": "",
    "origem": "passo201_detalheoferta"
  },
  {
    "pattern": "^/oimais\\/?$",
    "negativepattern": "",
    "etapa": "AUDIENCIA",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "OIMAIS",
    "pagina": "LP OIMAIS",
    "segmento": "MOBILIDADE",
    "canal": "",
    "origem": "passo201_detalheoferta"
  },
  {
    "pattern": "^/controle-boleto\\/?$",
    "negativepattern": "",
    "etapa": "AUDIENCIA",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "CONTROLE-BOLETO",
    "pagina": "LP CONTROLE BOLETO",
    "segmento": "MOBILIDADE",
    "canal": "",
    "origem": "passo201_detalheoferta"
  },
  {
    "pattern": "^\\/ofertas\\/assine-pos$",
    "negativepattern": "",
    "etapa": "AUDIENCIA",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP OFERTAS ASSINE POS",
    "segmento": "MOBILIDADE",
    "canal": "",
    "origem": "passo201_detalheoferta"
  },
  {
    "pattern": "^/celular-pos-pago\\/?$",
    "negativepattern": "",
    "etapa": "AUDIENCIA",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "POS-PAGO",
    "pagina": "P POS PAGO OCC",
    "segmento": "MOBILIDADE",
    "canal": "",
    "origem": "passo201_detalheoferta"
  },
  {
    "pattern": "^/fibra-otica\\/?$",
    "negativepattern": "",
    "etapa": "AUDIENCIA",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "FIBRA",
    "pagina": "P FIBRA",
    "segmento": "RESIDENCIAL",
    "canal": "",
    "origem": "passo201_detalheoferta"
  },
  {
    "pattern": "^/blackfriday\\/?$",
    "negativepattern": "",
    "etapa": "AUDIENCIA",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP POS-PAGO BLACKFRIDAY",
    "segmento": "MOBILIDADE",
    "canal": "",
    "origem": "passo222_black_friday.hql"
  },
  {
    "pattern": "^/static/assine-pos-a\\/?$",
    "negativepattern": "",
    "etapa": "AUDIENCIA",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP ASSINE POS A",
    "segmento": "MOBILIDADE",
    "canal": "",
    "origem": "passo244_lp_assine_pos_a"
  },
  {
    "pattern": "^/celular-pos-pago/detalhes-da-oferta/.*",
    "negativepattern": "",
    "etapa": "DETALHE DA OFERTA",
    "fluxo": "",
    "tipo": "PAGINA",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO OCC",
    "segmento": "MOBILIDADE",
    "canal": "",
    "origem": "passo201_detalheoferta"
  },
  {
    "pattern": ".*lp-pos_pago-black-friday/celular-pos-pago/detalhes-da-oferta.*",
    "negativepattern": "",
    "etapa": "DETALHE DA OFERTA",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP POS-PAGO BLACKFRIDAY",
    "segmento": "MOBILIDADE",
    "canal": "",
    "origem": "passo201_detalheoferta"
  },
  {
    "pattern": ".*carrinho.oi.com.br.*banda.*central_c2c.*",
    "negativepattern": "(sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "BANDA LARGA",
    "pagina": "P BANDA LARGA",
    "segmento": "RESIDENCIAL",
    "canal": "C2C",
    "origem": "passo202_carrinho"
  },
  {
    "pattern": ".*carrinho.oi.com.br.*banda.*central_chat.*",
    "negativepattern": "(sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "BANDA LARGA",
    "pagina": "P BANDA LARGA",
    "segmento": "RESIDENCIAL",
    "canal": "CHAT",
    "origem": "passo202_carrinho"
  },
  {
    "pattern": ".*carrinho.oi.com.br.*banda.*central_form.*sv-oi-cep|central_form\\/?$",
    "negativepattern": "(sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "BANDA LARGA",
    "pagina": "P BANDA LARGA",
    "segmento": "RESIDENCIAL",
    "canal": "FORM",
    "origem": "passo202_carrinho"
  },
  {
    "pattern": ".*carrinho.oi.com.br.*combo.*aba-c2c.*",
    "negativepattern": "(sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "COMBO",
    "pagina": "P COMBO",
    "segmento": "RESIDENCIAL",
    "canal": "C2C",
    "origem": "passo202_carrinho"
  },
  {
    "pattern": ".*carrinho.oi.com.br.*combo.*aba-chat.*",
    "negativepattern": "(sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "COMBO",
    "pagina": "P COMBO",
    "segmento": "RESIDENCIAL",
    "canal": "CHAT",
    "origem": "passo202_carrinho"
  },
  {
    "pattern": ".*carrinho.oi.com.br.*combo.*aba-form.*",
    "negativepattern": "(sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "COMBO",
    "pagina": "P COMBO",
    "segmento": "RESIDENCIAL",
    "canal": "FORM",
    "origem": "passo202_carrinho"
  },
  {
    "pattern": ".*/carrinho.oi.com.br.*/combo.*/5.*central_c2c.*",
    "negativepattern": "(sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "COMBO RESIDENCIAL",
    "pagina": "P COMBO RESIDENCIAL",
    "segmento": "RESIDENCIAL",
    "canal": "C2C",
    "origem": "passo202_carrinho"
  },
  {
    "pattern": ".*/carrinho.oi.com.br.*/combo.*/5.*central_chat.*",
    "negativepattern": "(sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "COMBO RESIDENCIAL",
    "pagina": "P COMBO RESIDENCIAL",
    "segmento": "RESIDENCIAL",
    "canal": "CHAT",
    "origem": "passo202_carrinho"
  },
  {
    "pattern": ".*/carrinho.oi.com.br.*/combo.*/5.*central_form.*",
    "negativepattern": "(sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "COMBO RESIDENCIAL",
    "pagina": "P COMBO RESIDENCIAL",
    "segmento": "RESIDENCIAL",
    "canal": "FORM",
    "origem": "passo202_carrinho"
  },
  {
    "pattern": ".*/carrinho.oi.com.br.*/combo.*/6.*central_c2c.*",
    "negativepattern": "(sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "COMBO CONECTADO",
    "pagina": "P COMBO CONECTADO",
    "segmento": "RESIDENCIAL",
    "canal": "C2C",
    "origem": "passo202_carrinho"
  },
  {
    "pattern": ".*/carrinho.oi.com.br.*/combo.*/6.*central_chat.*",
    "negativepattern": "(sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "COMBO CONECTADO",
    "pagina": "P COMBO CONECTADO",
    "segmento": "RESIDENCIAL",
    "canal": "CHAT",
    "origem": "passo202_carrinho"
  },
  {
    "pattern": ".*/carrinho.oi.com.br.*/combo.*/6.*central_form.*",
    "negativepattern": "(sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "COMBO CONECTADO",
    "pagina": "P COMBO CONECTADO",
    "segmento": "RESIDENCIAL",
    "canal": "FORM",
    "origem": "passo202_carrinho"
  },
  {
    "pattern": ".*/carrinho.oi.com.br.*/combo.*/7.*central_c2c.*",
    "negativepattern": "(sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "COMBO COMPLETO",
    "pagina": "P COMBO COMPLETO",
    "segmento": "RESIDENCIAL",
    "canal": "C2C",
    "origem": "passo202_carrinho"
  },
  {
    "pattern": ".*/carrinho.oi.com.br.*/combo.*/7.*central_chat.*",
    "negativepattern": "(sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "COMBO COMPLETO",
    "pagina": "P COMBO COMPLETO",
    "segmento": "RESIDENCIAL",
    "canal": "CHAT",
    "origem": "passo202_carrinho"
  },
  {
    "pattern": ".*/carrinho.oi.com.br.*/combo.*/7.*central_form.*",
    "negativepattern": "(sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "COMBO COMPLETO",
    "pagina": "P COMBO COMPLETO",
    "segmento": "RESIDENCIAL",
    "canal": "FORM",
    "origem": "passo202_carrinho"
  },
  {
    "pattern": ".*/carrinho.oi.com.br.*/combo.*/9.*central_c2c.*",
    "negativepattern": "(sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "COMBO OI PLAY",
    "pagina": "P COMBO OI PLAY",
    "segmento": "RESIDENCIAL",
    "canal": "C2C",
    "origem": "passo202_carrinho"
  },
  {
    "pattern": ".*/carrinho.oi.com.br.*/combo.*/9.*central_chat.*",
    "negativepattern": "(minha|banner|sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "COMBO OI PLAY",
    "pagina": "P COMBO OI PLAY",
    "segmento": "RESIDENCIAL",
    "canal": "CHAT",
    "origem": "passo202_carrinho_1"
  },
  {
    "pattern": ".*/carrinho.oi.com.br.*/combo.*/9.*central_form(.*sv-oi-cep|\\/?$)",
    "negativepattern": "(minha|banner|sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "COMBO OI PLAY",
    "pagina": "P COMBO OI PLAY",
    "segmento": "RESIDENCIAL",
    "canal": "FORM",
    "origem": "passo202_carrinho_1"
  },
  {
    "pattern": ".*/carrinho.oi.com.br.*/combo.*/8.*central_c2c.*",
    "negativepattern": "(minha|banner|sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "COMBO 2P TV",
    "pagina": "P COMBO 2P TV",
    "segmento": "RESIDENCIAL",
    "canal": "C2C",
    "origem": "passo202_carrinho_1"
  },
  {
    "pattern": ".*/carrinho.oi.com.br.*/combo.*/8.*central_chat.*",
    "negativepattern": "(minha|banner|sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "COMBO 2P TV",
    "pagina": "P COMBO 2P TV",
    "segmento": "RESIDENCIAL",
    "canal": "CHAT",
    "origem": "passo202_carrinho_1"
  },
  {
    "pattern": ".*/carrinho.oi.com.br.*/combo.*/8.*central_form.*",
    "negativepattern": "(minha|banner|sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "COMBO 2P TV",
    "pagina": "P COMBO 2P TV",
    "segmento": "RESIDENCIAL",
    "canal": "FORM",
    "origem": "passo202_carrinho_1"
  },
  {
    "pattern": ".*/carrinho.oi.com.br.*fixo.*aba-c2c.*",
    "negativepattern": "(minha|banner|sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "FIXO",
    "pagina": "P FIXO",
    "segmento": "RESIDENCIAL",
    "canal": "C2C",
    "origem": "passo202_carrinho_1"
  },
  {
    "pattern": ".*/carrinho.oi.com.br.*fixo.*aba-chat.*",
    "negativepattern": "(minha|banner|sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "FIXO",
    "pagina": "P FIXO",
    "segmento": "RESIDENCIAL",
    "canal": "CHAT",
    "origem": "passo202_carrinho_1"
  },
  {
    "pattern": ".*/carrinho.oi.com.br.*fixo.*aba-form.*",
    "negativepattern": "(minha|banner|sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "FIXO",
    "pagina": "P FIXO",
    "segmento": "RESIDENCIAL",
    "canal": "FORM",
    "origem": "passo202_carrinho_1"
  },
  {
    "pattern": "controle/.*(\\/?)central_c2c$|^/ecommerce-m/controle/c2c$",
    "negativepattern": "(minha|banner|sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "CONTROLE",
    "pagina": "P CONTROLE",
    "segmento": "MOBILIDADE",
    "canal": "C2C",
    "origem": "passo202_carrinho_1"
  },
  {
    "pattern": "controle/.*/central_chat$",
    "negativepattern": "(minha|banner|sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "CONTROLE",
    "pagina": "P CONTROLE",
    "segmento": "MOBILIDADE",
    "canal": "CHAT",
    "origem": "passo202_carrinho_1"
  },
  {
    "pattern": "^/migracao-.*controle/pre/triagem$",
    "negativepattern": "(landing_fluxo|landing_4g|minha|banner|sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "CONTROLE",
    "pagina": "P CONTROLE",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo202_carrinho_1"
  },
  {
    "pattern": "^/carrinho.oi.com.br/tv/aba-c2c$",
    "negativepattern": "(minha|banner|sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "TV",
    "pagina": "P TV",
    "segmento": "RESIDENCIAL",
    "canal": "C2C",
    "origem": "passo202_carrinho_1"
  },
  {
    "pattern": "^/carrinho.oi.com.br/tv/aba-chat$",
    "negativepattern": "(minha|banner|sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "TV",
    "pagina": "P TV",
    "segmento": "RESIDENCIAL",
    "canal": "CHAT",
    "origem": "passo202_carrinho_1"
  },
  {
    "pattern": "^/carrinho.oi.com.br/tv/aba-form$",
    "negativepattern": "(minha|banner|sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "TV",
    "pagina": "P TV",
    "segmento": "RESIDENCIAL",
    "canal": "FORM",
    "origem": "passo202_carrinho_1"
  },
  {
    "pattern": ".*/carrinho.oi.com.br.*combo.*landing_combo.*central_c2c.*",
    "negativepattern": "(minha|banner|sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "COMBO",
    "pagina": "LP ASSINE COMBO",
    "segmento": "RESIDENCIAL",
    "canal": "C2C",
    "origem": "passo202_carrinho_1"
  },
  {
    "pattern": ".*/carrinho.oi.com.br.*combo.*landing_combo.*central_chat.*",
    "negativepattern": "(minha|banner|sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "COMBO",
    "pagina": "LP ASSINE COMBO",
    "segmento": "RESIDENCIAL",
    "canal": "CHAT",
    "origem": "passo202_carrinho_1"
  },
  {
    "pattern": ".*/carrinho.oi.com.br.*tv.*landing_tv.*central_c2c.*",
    "negativepattern": "(minha|banner|sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "TV",
    "pagina": "LP ASSINE TV",
    "segmento": "RESIDENCIAL",
    "canal": "C2C",
    "origem": "passo202_carrinho_1"
  },
  {
    "pattern": ".*/carrinho.oi.com.br.*tv.*landing_tv.*central_chat.*",
    "negativepattern": "(minha|banner|sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "TV",
    "pagina": "LP ASSINE TV",
    "segmento": "RESIDENCIAL",
    "canal": "CHAT",
    "origem": "passo202_carrinho_1"
  },
  {
    "pattern": ".*/migracao-controle/.*migre.*landing_tv/.*central_c2c.*",
    "negativepattern": "(minha|banner|sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "CONTROLE",
    "pagina": "LP MIGRE-PRA-CONTROLE",
    "segmento": "MOBILIDADE",
    "canal": "C2C",
    "origem": "passo202_carrinho_1"
  },
  {
    "pattern": " .*/migracao-controle/.*migre.*landing_tv/.*central_chat.*",
    "negativepattern": "(minha|banner|sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "CONTROLE",
    "pagina": "LP MIGRE-PRA-CONTROLE",
    "segmento": "MOBILIDADE",
    "canal": "CHAT",
    "origem": "passo202_carrinho_1"
  },
  {
    "pattern": ".*/carrinho.oi.com.br/.*landing_convergente.*central_c2c.*",
    "negativepattern": "(minha|banner|sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "BANDA LARGA",
    "pagina": "LP 15MEGA",
    "segmento": "RESIDENCIAL",
    "canal": "C2C",
    "origem": "passo202_carrinho_1"
  },
  {
    "pattern": ".*/carrinho.oi.com.br/.*landing_convergente.*central_chat.*",
    "negativepattern": "(minha|banner|sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "BANDA LARGA",
    "pagina": "LP 15MEGA",
    "segmento": "RESIDENCIAL",
    "canal": "CHAT",
    "origem": "passo202_carrinho_1"
  },
  {
    "pattern": ".*/carrinho.oi.com.br/.*landing_convergente.*central_form.*",
    "negativepattern": "(minha|banner|sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "BANDA LARGA",
    "pagina": "LP 15MEGA",
    "segmento": "RESIDENCIAL",
    "canal": "FORM",
    "origem": "passo202_carrinho_1"
  },
  {
    "pattern": ".*/migracao-controle/.*landing_4g.*central_c2c.*",
    "negativepattern": "(minha|banner|sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "CONTROLE",
    "pagina": "LP 4G",
    "segmento": "MOBILIDADE",
    "canal": "C2C",
    "origem": "passo202_carrinho_1"
  },
  {
    "pattern": ".*/migracao-controle/.*landing_4g.*central_chat.*",
    "negativepattern": "(minha|banner|sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "CONTROLE",
    "pagina": "LP 4G",
    "segmento": "MOBILIDADE",
    "canal": "CHAT",
    "origem": "passo202_carrinho_1"
  },
  {
    "pattern": ".*pos.*occ.*central_c2c.*",
    "negativepattern": "(minha|banner|sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP OFERTAS ASSINE POS",
    "segmento": "MOBILIDADE",
    "canal": "C2C",
    "origem": "passo202_carrinho_1"
  },
  {
    "pattern": ".*pos.*occ.*central_chat.*",
    "negativepattern": "(minha|banner|sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP OFERTAS ASSINE POS",
    "segmento": "MOBILIDADE",
    "canal": "CHAT",
    "origem": "passo202_carrinho_1"
  },
  {
    "pattern": ".*/carrinho.oi.com.br/pospago/.*landing_4g.*central_c2c.*",
    "negativepattern": "(minha|banner|sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP 4G",
    "segmento": "MOBILIDADE",
    "canal": "C2C",
    "origem": "passo202_carrinho_1"
  },
  {
    "pattern": ".*/carrinho.oi.com.br/pospago/.*landing_4g.*central_chat.*",
    "negativepattern": "(minha|banner|sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP 4G",
    "segmento": "MOBILIDADE",
    "canal": "CHAT",
    "origem": "passo202_carrinho_1"
  },
  {
    "pattern": ".*/carrinho.oi.com.br/pospago/.*landing_4g.*central_form.*",
    "negativepattern": "(minha|banner|sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP 4G",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo202_carrinho_1"
  },
  {
    "pattern": "pos.*(oimais|lp_pos).*central_c2c\\/?$",
    "negativepattern": "(occ|minha|banner|sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP OIMAIS",
    "segmento": "MOBILIDADE",
    "canal": "C2C",
    "origem": "passo202_carrinho_1"
  },
  {
    "pattern": "pos.*(oimais|lp_pos).*central_chat\\/?$",
    "negativepattern": "(occ|minha|banner|sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP OIMAIS",
    "segmento": "MOBILIDADE",
    "canal": "CHAT",
    "origem": "passo202_carrinho_1"
  },
  {
    "pattern": "pos.*(oimais|lp_pos).*central_form\\/?$",
    "negativepattern": "(occ|minha|banner|sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP OIMAIS",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo202_carrinho_1"
  },
  {
    "pattern": ".*pos.*(lp_pos|landingoimais).*central_form/form.*opcoes.*",
    "negativepattern": "(occ|minha|banner|sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP OIMAIS",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo202_carrinho_1"
  },
  {
    "pattern": "^/oi.com.br/ecommerce/pospago/oi-c2c.html$|pos.*/central_c2c\\/?$",
    "negativepattern": "(occ|landing_4g|lp_pos|landingoimais|minha|banner|sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO",
    "segmento": "MOBILIDADE",
    "canal": "C2C",
    "origem": "passo202_carrinho_1"
  },
  {
    "pattern": "^/oi.com.br/ecommerce/pospago/oi-chat.html$|pos.*/central_chat\\/?$",
    "negativepattern": "(occ|landing_4g|lp_pos|landingoimais|minha|banner|sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO",
    "segmento": "MOBILIDADE",
    "canal": "CHAT",
    "origem": "passo202_carrinho_1"
  },
  {
    "pattern": "pos.*central_form/form.*opcoes",
    "negativepattern": "(occ|landing_4g|lp_pos|landingoimais|minha|banner|sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo202_carrinho_1"
  },
  {
    "pattern": "pos.*central_form/",
    "negativepattern": "(occ|landing_4g|lp_pos|landingoimais|minha|banner|sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo202_carrinho_1"
  },
  {
    "pattern": "carrinho.oi.com.br.*/pos-pago.*central_form.*dados-basicos",
    "negativepattern": "(aba|sucesso|landing|c2c|chat|plano|faq|empresas|/mgmtportaloiprd.telemar/|/localhost/).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO OCC",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo202_carrinho_1"
  },
  {
    "pattern": "carrinho.oi.com.br.*/pos-pago.*central_c2c",
    "negativepattern": "(aba|sucesso|landing|chat|form|plano|faq|empresas|/mgmtportaloiprd.telemar/|/localhost/).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO OCC",
    "segmento": "MOBILIDADE",
    "canal": "C2C",
    "origem": "passo202_carrinho_1"
  },
  {
    "pattern": "carrinho.oi.com.br.*/pos-pago.*central_chat",
    "negativepattern": "(aba|sucesso|landing|c2c|form|plano|faq|empresas|/mgmtportaloiprd.telemar/|/localhost/).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO OCC",
    "segmento": "MOBILIDADE",
    "canal": "CHAT",
    "origem": "passo202_carrinho_1"
  },
  {
    "pattern": "/assine-combo/aba-c2c/sucesso(-agendamento)?|landing_combo.*central_c2c.*sucesso",
    "negativepattern": "",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "COMBO",
    "pagina": "LP ASSINE COMBO",
    "segmento": "RESIDENCIAL",
    "canal": "C2C",
    "origem": "passo203_carrinho_sucesso"
  },
  {
    "pattern": "landing_combo.*central_chat.*iniciar",
    "negativepattern": "",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "COMBO",
    "pagina": "LP ASSINE COMBO",
    "segmento": "RESIDENCIAL",
    "canal": "CHAT",
    "origem": "passo203_carrinho_sucesso"
  },
  {
    "pattern": "assine-tv.*c2c.*sucesso",
    "negativepattern": "",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "TV",
    "pagina": "LP ASSINE TV",
    "segmento": "RESIDENCIAL",
    "canal": "C2C",
    "origem": "passo203_carrinho_sucesso"
  },
  {
    "pattern": "landing_tv.*central_c2c.*sucesso",
    "negativepattern": "",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "TV",
    "pagina": "LP ASSINE TV",
    "segmento": "RESIDENCIAL",
    "canal": "C2C",
    "origem": "passo203_carrinho_sucesso"
  },
  {
    "pattern": "(assine-tv|landing_tv).*(central_)?chat.*(sucesso|iniciar)",
    "negativepattern": "",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "TV",
    "pagina": "LP ASSINE TV",
    "segmento": "RESIDENCIAL",
    "canal": "CHAT",
    "origem": "passo203_carrinho_sucesso"
  },
  {
    "pattern": "15mega.*c2c.*sucesso",
    "negativepattern": "",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "BANDA LARGA",
    "pagina": "LP 15MEGA",
    "segmento": "RESIDENCIAL",
    "canal": "C2C",
    "origem": "passo203_carrinho_sucesso"
  },
  {
    "pattern": "landing_convergente.*central_c2c.*sucesso",
    "negativepattern": "",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "BANDA LARGA",
    "pagina": "LP 15MEGA",
    "segmento": "RESIDENCIAL",
    "canal": "C2C",
    "origem": "passo203_carrinho_sucesso"
  },
  {
    "pattern": "15mega.*(aba-)?chat.*sucesso",
    "negativepattern": "",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "BANDA LARGA",
    "pagina": "LP 15MEGA",
    "segmento": "RESIDENCIAL",
    "canal": "CHAT",
    "origem": "passo203_carrinho_sucesso"
  },
  {
    "pattern": "15mega.*(aba-)?chat.*iniciar",
    "negativepattern": "",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "BANDA LARGA",
    "pagina": "LP 15MEGA",
    "segmento": "RESIDENCIAL",
    "canal": "CHAT",
    "origem": "passo203_carrinho_sucesso"
  },
  {
    "pattern": "assine-controle.*c2c.*sucesso",
    "negativepattern": "",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "CONTROLE",
    "pagina": "LP ASSINE CONTROLE",
    "segmento": "MOBILIDADE",
    "canal": "C2C",
    "origem": "passo203_carrinho_sucesso"
  },
  {
    "pattern": "assine-controle.*chat.*sucesso",
    "negativepattern": "",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "CONTROLE",
    "pagina": "LP ASSINE CONTROLE",
    "segmento": "MOBILIDADE",
    "canal": "CHAT",
    "origem": "passo203_carrinho_sucesso"
  },
  {
    "pattern": "migracao-controle/.*cart_all_migre/central_c2c/(iniciar|agendamento.*sucesso)",
    "negativepattern": "",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "CONTROLE",
    "pagina": "LP MIGRE CONTROLE",
    "segmento": "MOBILIDADE",
    "canal": "C2C",
    "origem": "passo203_carrinho_sucesso"
  },
  {
    "pattern": "migracao-controle/.*cart_all_migre/central_chat/(iniciar|agendamento.*sucesso)",
    "negativepattern": "",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "CONTROLE",
    "pagina": "LP MIGRE CONTROLE",
    "segmento": "MOBILIDADE",
    "canal": "CHAT",
    "origem": "passo203_carrinho_sucesso"
  },
  {
    "pattern": "migracao-controle/.*cart_all_migrar/central_c2c/(iniciar|agendamento.*sucesso)",
    "negativepattern": "",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "CONTROLE",
    "pagina": "LP MIGRAR CONTROLE",
    "segmento": "MOBILIDADE",
    "canal": "C2C",
    "origem": "passo203_carrinho_sucesso"
  },
  {
    "pattern": "migracao-controle/.*cart_all_migrar/central_chat/(iniciar|agendamento.*sucesso)",
    "negativepattern": "",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "CONTROLE",
    "pagina": "LP MIGRAR CONTROLE",
    "segmento": "MOBILIDADE",
    "canal": "CHAT",
    "origem": "passo203_carrinho_sucesso"
  },
  {
    "pattern": "/4g/c2c/sucesso|/carrinho.oi.com.br/(controle|pospago).*landing_4g/central_c2c/(iniciar|agendamento.*sucesso)",
    "negativepattern": "",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "CONTROLE",
    "pagina": "LP 4G",
    "segmento": "MOBILIDADE",
    "canal": "C2C",
    "origem": "passo203_carrinho_sucesso"
  },
  {
    "pattern": "/4g/chat/sucesso|/carrinho.oi.com.br/(controle|pospago).*landing_4g/central_chat/(iniciar|agendamento.*sucesso)",
    "negativepattern": "",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "CONTROLE",
    "pagina": "LP 4G",
    "segmento": "MOBILIDADE",
    "canal": "CHAT",
    "origem": "passo203_carrinho_sucesso"
  },
  {
    "pattern": "banda.*central_c2c.*sucesso",
    "negativepattern": "",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "BANDA LARGA",
    "pagina": "P BANDA LARGA",
    "segmento": "RESIDENCIAL",
    "canal": "C2C",
    "origem": "passo203_carrinho_sucesso"
  },
  {
    "pattern": "banda.*central_chat.*sucesso",
    "negativepattern": "",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "BANDA LARGA",
    "pagina": "P BANDA LARGA",
    "segmento": "RESIDENCIAL",
    "canal": "CHAT",
    "origem": "passo203_carrinho_sucesso"
  },
  {
    "pattern": "banda.*central_form.*sucesso",
    "negativepattern": "",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "BANDA LARGA",
    "pagina": "P BANDA LARGA",
    "segmento": "RESIDENCIAL",
    "canal": "FORM",
    "origem": "passo203_carrinho_sucesso"
  },
  {
    "pattern": "^/carrinho.oi.com.br/fixo/aba-c2c/sucesso$",
    "negativepattern": "",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "FIXO",
    "pagina": "P FIXO",
    "segmento": "RESIDENCIAL",
    "canal": "C2C",
    "origem": "passo203_carrinho_sucesso"
  },
  {
    "pattern": "^/carrinho.oi.com.br/fixo/(aba-)?chat/sucesso$",
    "negativepattern": "",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "FIXO",
    "pagina": "P FIXO",
    "segmento": "RESIDENCIAL",
    "canal": "CHAT",
    "origem": "passo203_carrinho_sucesso"
  },
  {
    "pattern": "^/carrinho.oi.com.br/fixo/aba-form/sucesso$",
    "negativepattern": "",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "FIXO",
    "pagina": "P FIXO",
    "segmento": "RESIDENCIAL",
    "canal": "FORM",
    "origem": "passo203_carrinho_sucesso"
  },
  {
    "pattern": "^/carrinho.oi.com.br/tv/aba-c2c/sucesso$",
    "negativepattern": "",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "TV",
    "pagina": "P TV",
    "segmento": "RESIDENCIAL",
    "canal": "C2C",
    "origem": "passo203_carrinho_sucesso"
  },
  {
    "pattern": "^/carrinho.oi.com.br/tv/chat/sucesso$",
    "negativepattern": "",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "TV",
    "pagina": "P TV",
    "segmento": "RESIDENCIAL",
    "canal": "CHAT",
    "origem": "passo203_carrinho_sucesso_1"
  },
  {
    "pattern": "/carrinho.oi.com.br.*/combo.*/5.*central_c2c.*(iniciar|agendamento.*sucesso)",
    "negativepattern": "",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "COMBO RESIDENCIAL",
    "pagina": "P COMBO RESIDENCIAL",
    "segmento": "RESIDENCIAL",
    "canal": "C2C",
    "origem": "passo203_carrinho_sucesso_1"
  },
  {
    "pattern": "/carrinho.oi.com.br.*/combo.*/5.*central_chat.*(iniciar|agendamento.*sucesso)",
    "negativepattern": "",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "COMBO RESIDENCIAL",
    "pagina": "P COMBO RESIDENCIAL",
    "segmento": "RESIDENCIAL",
    "canal": "CHAT",
    "origem": "passo203_carrinho_sucesso_1"
  },
  {
    "pattern": "/carrinho.oi.com.br.*/combo.*/5.*central_form.*(iniciar|agendamento.*sucesso)",
    "negativepattern": "",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "COMBO RESIDENCIAL",
    "pagina": "P COMBO RESIDENCIAL",
    "segmento": "RESIDENCIAL",
    "canal": "FORM",
    "origem": "passo203_carrinho_sucesso_1"
  },
  {
    "pattern": "/carrinho.oi.com.br.*/combo.*/6.*central_c2c.*(iniciar|agendamento.*sucesso)",
    "negativepattern": "",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "COMBO CONECTADO",
    "pagina": "P COMBO CONECTADO",
    "segmento": "RESIDENCIAL",
    "canal": "C2C",
    "origem": "passo203_carrinho_sucesso_1"
  },
  {
    "pattern": "/carrinho.oi.com.br.*/combo.*/6.*central_chat.*(iniciar|agendamento.*sucesso)",
    "negativepattern": "",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "COMBO CONECTADO",
    "pagina": "P COMBO CONECTADO",
    "segmento": "RESIDENCIAL",
    "canal": "CHAT",
    "origem": "passo203_carrinho_sucesso_1"
  },
  {
    "pattern": "/carrinho.oi.com.br.*/combo.*/6.*central_form.*(iniciar|agendamento.*sucesso)",
    "negativepattern": "",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "COMBO CONECTADO",
    "pagina": "P COMBO CONECTADO",
    "segmento": "RESIDENCIAL",
    "canal": "FORM",
    "origem": "passo203_carrinho_sucesso_1"
  },
  {
    "pattern": "/carrinho.oi.com.br.*/combo.*/7.*central_c2c.*(iniciar|agendamento.*sucesso)",
    "negativepattern": "",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "COMBO COMPLETO",
    "pagina": "P COMBO COMPLETO",
    "segmento": "RESIDENCIAL",
    "canal": "C2C",
    "origem": "passo203_carrinho_sucesso_1"
  },
  {
    "pattern": "/carrinho.oi.com.br.*/combo.*/7.*central_chat.*(iniciar|agendamento.*sucesso)",
    "negativepattern": "",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "COMBO COMPLETO",
    "pagina": "P COMBO COMPLETO",
    "segmento": "RESIDENCIAL",
    "canal": "CHAT",
    "origem": "passo203_carrinho_sucesso_1"
  },
  {
    "pattern": "/carrinho.oi.com.br.*/combo.*/7.*central_form.*(iniciar|agendamento.*sucesso)",
    "negativepattern": "",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "COMBO COMPLETO",
    "pagina": "P COMBO COMPLETO",
    "segmento": "RESIDENCIAL",
    "canal": "FORM",
    "origem": "passo203_carrinho_sucesso_1"
  },
  {
    "pattern": "/carrinho.oi.com.br.*/combo.*/9.*central_c2c.*(iniciar|agendamento.*sucesso)",
    "negativepattern": "",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "COMBO OI PLAY",
    "pagina": "P COMBO OI PLAY",
    "segmento": "RESIDENCIAL",
    "canal": "C2C",
    "origem": "passo203_carrinho_sucesso_1"
  },
  {
    "pattern": "/carrinho.oi.com.br.*/combo.*/9.*central_chat.*(iniciar|agendamento.*sucesso)",
    "negativepattern": "",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "COMBO OI PLAY",
    "pagina": "P COMBO OI PLAY",
    "segmento": "RESIDENCIAL",
    "canal": "CHAT",
    "origem": "passo203_carrinho_sucesso_1"
  },
  {
    "pattern": "/carrinho.oi.com.br.*/combo.*/9.*central_form.*(iniciar|agendamento.*sucesso)",
    "negativepattern": "",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "COMBO OI PLAY",
    "pagina": "P COMBO OI PLAY",
    "segmento": "RESIDENCIAL",
    "canal": "FORM",
    "origem": "passo203_carrinho_sucesso_1"
  },
  {
    "pattern": "/carrinho.oi.com.br.*/combo.*/8.*central_c2c.*(iniciar|agendamento.*sucesso)",
    "negativepattern": "",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "COMBO 2P TV",
    "pagina": "P COMBO 2P TV",
    "segmento": "RESIDENCIAL",
    "canal": "C2C",
    "origem": "passo203_carrinho_sucesso_1"
  },
  {
    "pattern": "/carrinho.oi.com.br.*/combo.*/8.*central_chat.*(iniciar|agendamento.*sucesso)",
    "negativepattern": "",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "COMBO 2P TV",
    "pagina": "P COMBO 2P TV",
    "segmento": "RESIDENCIAL",
    "canal": "CHAT",
    "origem": "passo203_carrinho_sucesso_1"
  },
  {
    "pattern": "/carrinho.oi.com.br.*/combo.*/8.*central_form.*(iniciar|agendamento.*sucesso)",
    "negativepattern": "",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "COMBO 2P TV",
    "pagina": "P COMBO 2P TV",
    "segmento": "RESIDENCIAL",
    "canal": "FORM",
    "origem": "passo203_carrinho_sucesso_1"
  },
  {
    "pattern": "migracao-controle.*/central_c2c/(iniciar|agendamento.*sucesso)",
    "negativepattern": "",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "CONTROLE",
    "pagina": "P CONTROLE",
    "segmento": "MOBILIDADE",
    "canal": "C2C",
    "origem": "passo203_carrinho_sucesso_1"
  },
  {
    "pattern": "migracao-controle.*/central_c2c/(iniciar|agendamento.*sucesso)",
    "negativepattern": "",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "CONTROLE",
    "pagina": "P CONTROLE",
    "segmento": "MOBILIDADE",
    "canal": "CHAT",
    "origem": "passo203_carrinho_sucesso_1"
  },
  {
    "pattern": "/migracao-pre-controle/sucesso-sem-saldo|/migracao-pre-controle/cartao/sucesso|/migracao-pre-controle/boleto/sucesso|/migracao-pre-controle/boleto/sucesso-sem-saldo",
    "negativepattern": "",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "CONTROLE",
    "pagina": "P CONTROLE",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo203_carrinho_sucesso_1"
  },
  {
    "pattern": "/carrinho.oi.com.br/aba-c2c/sucesso.*occ.*central_c2c.*(sucesso|iniciar)",
    "negativepattern": "",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP OFERTAS ASSINE POS",
    "segmento": "MOBILIDADE",
    "canal": "C2C",
    "origem": "passo203_carrinho_sucesso_1"
  },
  {
    "pattern": "assine-pos.*c2c.*sucesso",
    "negativepattern": "",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP ASSINE POS",
    "segmento": "MOBILIDADE",
    "canal": "C2C",
    "origem": "passo203_carrinho_sucesso_1"
  },
  {
    "pattern": "assine-pos.*chat.*sucesso",
    "negativepattern": "",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP ASSINE POS",
    "segmento": "MOBILIDADE",
    "canal": "CHAT",
    "origem": "passo203_carrinho_sucesso_1"
  },
  {
    "pattern": "pos.*/central_c2c/sucesso_op.*(lp_pos|oimais)",
    "negativepattern": "(occ|landing_4g|minha|banner|empresas|moi|cart\\/?$).*",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP OIMAIS",
    "segmento": "MOBILIDADE",
    "canal": "C2C",
    "origem": "passo203_carrinho_sucesso_1"
  },
  {
    "pattern": "pos.*/central_chat/sucesso_op.*(lp_pos|oimais)",
    "negativepattern": "(occ|landing_4g|minha|banner|empresas|moi|cart\\/?$).*",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP OIMAIS",
    "segmento": "MOBILIDADE",
    "canal": "CHAT",
    "origem": "passo203_carrinho_sucesso_1"
  },
  {
    "pattern": "pos.*/central_form/sucesso_op.*(lp_pos|oimais)",
    "negativepattern": "(occ|landing_4g|minha|banner|empresas|moi|cart\\/?$).*",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP OIMAIS",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo203_carrinho_sucesso_1"
  },
  {
    "pattern": "pos.*landing_4g.*central_c2c.*central_c2c",
    "negativepattern": "",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP 4G",
    "segmento": "MOBILIDADE",
    "canal": "C2C",
    "origem": "passo203_carrinho_sucesso_1"
  },
  {
    "pattern": "pos.*landing_4g.*central_chat.*central_c2c",
    "negativepattern": "",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP 4G",
    "segmento": "MOBILIDADE",
    "canal": "CHAT",
    "origem": "passo203_carrinho_sucesso_1"
  },
  {
    "pattern": "pos.*landing_4g.*central_form.*central_c2c",
    "negativepattern": "",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP 4G",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo203_carrinho_sucesso_1"
  },
  {
    "pattern": "^/oi.com.br/ecommerce/pospago/oi-c2c-sucesso.html$",
    "negativepattern": "",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO",
    "segmento": "MOBILIDADE",
    "canal": "C2C",
    "origem": "passo203_carrinho_sucesso_1"
  },
  {
    "pattern": "pos.*/central_c2c\\/?.*sucesso-op",
    "negativepattern": "(occ|landing_4g|lp_pos|landingoimais|minha|banner|empresas|moi|cart\\/?$).*",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO",
    "segmento": "MOBILIDADE",
    "canal": "C2C",
    "origem": "passo203_carrinho_sucesso_1"
  },
  {
    "pattern": "^/oi.com.br/ecommerce/pospago/oi-chat-sucesso.html$",
    "negativepattern": "",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO",
    "segmento": "MOBILIDADE",
    "canal": "CHAT",
    "origem": "passo203_carrinho_sucesso_1"
  },
  {
    "pattern": "pos.*/central_chat\\/?.*sucesso-op",
    "negativepattern": "(occ|landing_4g|lp_pos|landingoimais|minha|banner|empresas|moi|cart\\/?$).*",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO",
    "segmento": "MOBILIDADE",
    "canal": "CHAT",
    "origem": "passo203_carrinho_sucesso_1"
  },
  {
    "pattern": "pos.*/central_form/(form.*sucesso|sucesso_op)",
    "negativepattern": "(occ|landing_4g|lp_pos|landingoimais|minha|banner|empresas|moi|cart\\/?$).*",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "PRODUTO",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo203_carrinho_sucesso_1"
  },
  {
    "pattern": "carrinho.oi.com.br.*pos-pago.*central_c2c.*sucesso_op",
    "negativepattern": "",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "PAGINA",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO OCC",
    "segmento": "MOBILIDADE",
    "canal": "C2C",
    "origem": "passo203_carrinho_sucesso_1"
  },
  {
    "pattern": "carrinho.oi.com.br.*pos-pago.*central_chat.*sucesso_op",
    "negativepattern": "",
    "etapa": "CARRINHO SUCESSO",
    "fluxo": "",
    "tipo": "PAGINA",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO OCC",
    "segmento": "MOBILIDADE",
    "canal": "CHAT",
    "origem": "passo203_carrinho_sucesso_1"
  },
  {
    "pattern": "(/carrinho.oi.com.br/pos-pago.*central_form/dados-basicos).*",
    "negativepattern": "(aba|sucesso|landing|c2c|chat|plano|faq|lp-pos_pago-black-friday|empresas|/mgmtportaloiprd.telemar/|/localhost/|migracao|portabilidade|nova-linha).*",
    "etapa": "CHECKOUT - DADOS BASICOS",
    "fluxo": "",
    "tipo": "PAGINA",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO OCC",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo204_checkout"
  },
  {
    "pattern": "(/carrinho.oi.com.br/pos-pago.*central_form/forma-ativacao).*",
    "negativepattern": "(dependente|aba|sucesso|landing|c2c|chat|plano|faq|lp-pos_pago-black-friday|empresas|/mgmtportaloiprd.telemar/|/localhost/|migracao|portabilidade|nova-linha).*",
    "etapa": "CHECKOUT - FORMA ATIVACAO",
    "fluxo": "",
    "tipo": "PAGINA",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO OCC",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo204_checkout"
  },
  {
    "pattern": "(carrinho.oi.com.br/pos-pago/checkout.*/central_form/migracao/token).*",
    "negativepattern": "(dependente|aba|sucesso|landing|c2c|chat|plano|faq|lp-pos_pago-black-friday|empresas|/mgmtportaloiprd.telemar/|/localhost/|portabilidade|nova-linha).*",
    "etapa": "CHECKOUT - TOKEN/OPERADORA",
    "fluxo": "POS - MIGRACAO",
    "tipo": "PAGINA",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO OCC",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo204_checkout"
  },
  {
    "pattern": "(carrinho.oi.com.br/pos-pago/checkout.*/central_form/portabilidade/operadora).*",
    "negativepattern": "(dependente|aba|sucesso|landing|c2c|chat|plano|faq|lp-pos_pago-black-friday|empresas|/mgmtportaloiprd.telemar/|/localhost/|migracao|nova-linha).*",
    "etapa": "CHECKOUT - TOKEN/OPERADORA",
    "fluxo": "POS - PORTABILIDADE",
    "tipo": "PAGINA",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO OCC",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo204_checkout"
  },
  {
    "pattern": "(/carrinho.oi.com.br/pos-pago.*central_form/.*nova-linha.*dados-pessoais).*",
    "negativepattern": "(aba|sucesso|landing|c2c|chat|plano|faq|lp-pos_pago-black-friday|empresas|/mgmtportaloiprd.telemar/|/localhost/|sucesso|invalido|abandono|incorreto|migracao|portabilidade).*",
    "etapa": "CHECKOUT - DADOS PESSOAIS",
    "fluxo": "POS - NOVA LINHA",
    "tipo": "PAGINA",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO OCC",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo204_checkout"
  },
  {
    "pattern": "(/carrinho.oi.com.br/pos-pago.*central_form/.*migracao.*dados-pessoais).*",
    "negativepattern": "(aba|sucesso|landing|c2c|chat|plano|faq|lp-pos_pago-black-friday|empresas|/mgmtportaloiprd.telemar/|/localhost/|sucesso|invalido|abandono|incorreto|portabilidade|nova-linha).*",
    "etapa": "CHECKOUT - DADOS PESSOAIS",
    "fluxo": "POS - MIGRACAO",
    "tipo": "PAGINA",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO OCC",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo204_checkout"
  },
  {
    "pattern": "(/carrinho.oi.com.br/pos-pago.*central_form/.*portabilidade.*dados-pessoais).*",
    "negativepattern": "(aba|sucesso|landing|c2c|chat|plano|faq|lp-pos_pago-black-friday|empresas|/mgmtportaloiprd.telemar/|/localhost/|sucesso|invalido|abandono|incorreto|migracao|nova-linha).*",
    "etapa": "CHECKOUT - DADOS PESSOAIS",
    "fluxo": "POS - PORTABILIDADE",
    "tipo": "PAGINA",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO OCC",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo204_checkout"
  },
  {
    "pattern": "(/carrinho.oi.com.br/pos-pago.*central_form/.*nova-linha/endereco).*",
    "negativepattern": "(aba|sucesso|landing|c2c|chat|plano|faq|lp-pos_pago-black-friday|empresas|/mgmtportaloiprd.telemar/|/localhost/|sucesso|invalido|abandono|incorreto|migracao|portabilidade).*",
    "etapa": "CHECKOUT - ENDERECO",
    "fluxo": "POS - NOVA LINHA",
    "tipo": "PAGINA",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO OCC",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo204_checkout"
  },
  {
    "pattern": "(/carrinho.oi.com.br/pos-pago.*central_form/.*migracao/endereco).*",
    "negativepattern": "(aba|sucesso|landing|c2c|chat|plano|faq|lp-pos_pago-black-friday|empresas|/mgmtportaloiprd.telemar/|/localhost/|sucesso|invalido|abandono|incorreto|portabilidade|nova-linha).*",
    "etapa": "CHECKOUT - ENDERECO",
    "fluxo": "POS - MIGRACAO",
    "tipo": "PAGINA",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO OCC",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo204_checkout"
  },
  {
    "pattern": "(/carrinho.oi.com.br/pos-pago.*central_form/.*portabilidade/endereco).*",
    "negativepattern": "(aba|sucesso|landing|c2c|chat|plano|faq|lp-pos_pago-black-friday|empresas|/mgmtportaloiprd.telemar/|/localhost/|sucesso|invalido|abandono|incorreto|migracao|nova-linha).*",
    "etapa": "CHECKOUT - ENDERECO",
    "fluxo": "POS - PORTABILIDADE",
    "tipo": "PAGINA",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO OCC",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo204_checkout"
  },
  {
    "pattern": "(/carrinho.oi.com.br/pos-pago.*central_form/nova-linha/cobranca).*",
    "negativepattern": "(aba|sucesso|landing|c2c|chat|plano|faq|lp-pos_pago-black-friday|empresas|/mgmtportaloiprd.telemar/|/localhost/|sucesso|invalido|abandono|incorreto|migracao|portabilidade).*",
    "etapa": "CHECKOUT - COBRANCA",
    "fluxo": "POS - NOVA LINHA",
    "tipo": "PAGINA",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO OCC",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo204_checkout"
  },
  {
    "pattern": "(/carrinho.oi.com.br/pos-pago.*central_form/migracao/cobranca).*",
    "negativepattern": "(aba|sucesso|landing|c2c|chat|plano|faq|lp-pos_pago-black-friday|empresas|/mgmtportaloiprd.telemar/|/localhost/|sucesso|invalido|abandono|incorreto|portabilidade|nova-linha).*",
    "etapa": "CHECKOUT - COBRANCA",
    "fluxo": "POS - MIGRACAO",
    "tipo": "PAGINA",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO OCC",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo204_checkout"
  },
  {
    "pattern": "(/carrinho.oi.com.br/pos-pago.*central_form/portabilidade/cobranca).*",
    "negativepattern": "(aba|sucesso|landing|c2c|chat|plano|faq|lp-pos_pago-black-friday|empresas|/mgmtportaloiprd.telemar/|/localhost/|sucesso|invalido|abandono|incorreto|migracao|nova-linha).*",
    "etapa": "CHECKOUT - COBRANCA",
    "fluxo": "POS - PORTABILIDADE",
    "tipo": "PAGINA",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO OCC",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo204_checkout"
  },
  {
    "pattern": "(/carrinho.oi.com.br/pos-pago.*central_form/nova-linha/vencimento).*",
    "negativepattern": "(aba|sucesso|landing|c2c|chat|plano|faq|lp-pos_pago-black-friday|empresas|/mgmtportaloiprd.telemar/|/localhost/|sucesso|invalido|abandono|incorreto|migracao|portabilidade).*",
    "etapa": "CHECKOUT - VENCIMENTO",
    "fluxo": "POS - NOVA LINHA",
    "tipo": "PAGINA",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO OCC",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo204_checkout"
  },
  {
    "pattern": "(/carrinho.oi.com.br/pos-pago.*central_form/migracao/vencimento).*",
    "negativepattern": "(aba|sucesso|landing|c2c|chat|plano|faq|lp-pos_pago-black-friday|empresas|/mgmtportaloiprd.telemar/|/localhost/|sucesso|invalido|abandono|incorreto|portabilidade|nova-linha).*",
    "etapa": "CHECKOUT - VENCIMENTO",
    "fluxo": "POS - MIGRACAO",
    "tipo": "PAGINA",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO OCC",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo204_checkout"
  },
  {
    "pattern": "(/carrinho.oi.com.br/pos-pago.*central_form/portabilidade/vencimento).*",
    "negativepattern": "(aba|sucesso|landing|c2c|chat|plano|faq|lp-pos_pago-black-friday|empresas|/mgmtportaloiprd.telemar/|/localhost/|sucesso|invalido|abandono|incorreto|migracao|nova-linha).*",
    "etapa": "CHECKOUT - VENCIMENTO",
    "fluxo": "POS - PORTABILIDADE",
    "tipo": "PAGINA",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO OCC",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo204_checkout"
  },
  {
    "pattern": "(/carrinho.oi.com.br/pos-pago.*central_form/.*nova-linha/revisar-dados).*",
    "negativepattern": "(aba|sucesso|landing|c2c|chat|plano|faq|lp-pos_pago-black-friday|empresas|/mgmtportaloiprd.telemar/|/localhost/|sucesso|invalido|abandono|incorreto|migracao|portabilidade).*",
    "etapa": "CHECKOUT - REVISAR DADOS",
    "fluxo": "POS - NOVA LINHA",
    "tipo": "PAGINA",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO OCC",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo204_checkout"
  },
  {
    "pattern": "(/carrinho.oi.com.br/pos-pago.*central_form/.*migracao/revisar-dados).*",
    "negativepattern": "(aba|sucesso|landing|c2c|chat|plano|faq|lp-pos_pago-black-friday|empresas|/mgmtportaloiprd.telemar/|/localhost/|sucesso|invalido|abandono|incorreto|portabilidade|nova-linha).*",
    "etapa": "CHECKOUT - REVISAR DADOS",
    "fluxo": "POS - MIGRACAO",
    "tipo": "PAGINA",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO OCC",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo204_checkout"
  },
  {
    "pattern": "(/carrinho.oi.com.br/pos-pago.*central_form/.*portabilidade/revisar-dados).*",
    "negativepattern": "(aba|sucesso|landing|c2c|chat|plano|faq|lp-pos_pago-black-friday|empresas|/mgmtportaloiprd.telemar/|/localhost/|sucesso|invalido|abandono|incorreto|migracao|nova-linha).*",
    "etapa": "CHECKOUT - REVISAR DADOS",
    "fluxo": "POS - PORTABILIDADE",
    "tipo": "PAGINA",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO OCC",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo204_checkout"
  },
  {
    "pattern": "(carrinho.oi.com.br/pos-pago.*central_form.*nova-linha\\/sucesso).*",
    "negativepattern": "(lp-pos_pago-black-friday).*",
    "etapa": "CARRINHO - SUCESSO",
    "fluxo": "POS - NOVA LINHA",
    "tipo": "PAGINA",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO OCC",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo204_checkout"
  },
  {
    "pattern": "(carrinho.oi.com.br/pos-pago.*central_form.*migracao\\/sucesso).*",
    "negativepattern": "(lp-pos_pago-black-friday).*",
    "etapa": "CARRINHO - SUCESSO",
    "fluxo": "POS - MIGRACAO",
    "tipo": "PAGINA",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO OCC",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo204_checkout"
  },
  {
    "pattern": "(carrinho.oi.com.br/pos-pago.*central_form.*portabilidade\\/sucesso).*",
    "negativepattern": "(lp-pos_pago-black-friday).*",
    "etapa": "CARRINHO - SUCESSO",
    "fluxo": "POS - PORTABILIDADE",
    "tipo": "PAGINA",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO OCC",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo204_checkout"
  },
  {
    "pattern": "^/lp-rentabilizacao/hbo\\/?$",
    "negativepattern": "(aba|sucesso|c2c|chat|form|plano|faq).*",
    "etapa": "AUDIENCIA",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "TV",
    "pagina": "LP RENT ASSINE HBO",
    "segmento": "RESIDENCIAL",
    "canal": "FORM",
    "origem": "passo221_rentabilizacao"
  },
  {
    "pattern": "^/lp-rentabilizacao/telecine\\/?$",
    "negativepattern": "(aba|sucesso|c2c|chat|form|plano|faq).*",
    "etapa": "AUDIENCIA",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "TV",
    "pagina": "LP RENT ASSINE TELECINE",
    "segmento": "RESIDENCIAL",
    "canal": "FORM",
    "origem": "passo221_rentabilizacao"
  },
  {
    "pattern": "^/lp-rentabilizacao/foxpremium.*",
    "negativepattern": "(aba|sucesso|c2c|chat|form|plano|faq).*",
    "etapa": "AUDIENCIA",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "TV",
    "pagina": "LP RENT ASSINE FOXPREMIUM",
    "segmento": "RESIDENCIAL",
    "canal": "FORM",
    "origem": "passo221_rentabilizacao"
  },
  {
    "pattern": "^/lp-rentabilizacao/tv-hd/formulario.*",
    "negativepattern": "(aba|sucesso|c2c|chat|plano|faq).*",
    "etapa": "AUDIENCIA",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "TV",
    "pagina": "LP RENT ASSINE CANAISTV",
    "segmento": "RESIDENCIAL",
    "canal": "FORM",
    "origem": "passo221_rentabilizacao"
  },
  {
    "pattern": "^/lpclientebl-aumente-bandalarga.*",
    "negativepattern": "(aba|sucesso|c2c|chat|form|plano|faq).*",
    "etapa": "AUDIENCIA",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "TV",
    "pagina": "LP RENT AUMENTE_BL",
    "segmento": "RESIDENCIAL",
    "canal": "FORM",
    "origem": "passo221_rentabilizacao"
  },
  {
    "pattern": "^/lp-rentabilizacao/hbo/sucesso.*",
    "negativepattern": "",
    "etapa": "CARRINHO - SUCESSO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "TV",
    "pagina": "LP RENT ASSINE HBO",
    "segmento": "RESIDENCIAL",
    "canal": "FORM",
    "origem": "passo221_rentabilizacao"
  },
  {
    "pattern": "^/lp-rentabilizacao/telecine/sucesso.*",
    "negativepattern": "",
    "etapa": "CARRINHO - SUCESSO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "TV",
    "pagina": "LP RENT ASSINE TELECINE",
    "segmento": "RESIDENCIAL",
    "canal": "FORM",
    "origem": "passo221_rentabilizacao"
  },
  {
    "pattern": "^/lp-rentabilizacao/foxpremium.*sucesso",
    "negativepattern": "",
    "etapa": "CARRINHO - SUCESSO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "TV",
    "pagina": "LP RENT ASSINE FOXPREMIUM",
    "segmento": "RESIDENCIAL",
    "canal": "FORM",
    "origem": "passo221_rentabilizacao"
  },
  {
    "pattern": "/lp-rentabilizacao/tv-hd.*(cart_form|central_form).*sucesso",
    "negativepattern": "",
    "etapa": "CARRINHO - SUCESSO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "TV",
    "pagina": "LP RENT ASSINE CANAISTV",
    "segmento": "RESIDENCIAL",
    "canal": "FORM",
    "origem": "passo221_rentabilizacao"
  },
  {
    "pattern": "^/carrinho.oi.com.br.*cart_all_rentabilizacao.*data_c2c.*sucesso",
    "negativepattern": "",
    "etapa": "CARRINHO - SUCESSO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "TV",
    "pagina": "LP RENT AUMENTE_BL",
    "segmento": "RESIDENCIAL",
    "canal": "FORM",
    "origem": "passo221_rentabilizacao"
  },
  {
    "pattern": "^/lp-rentabilizacao/tv-hd.*central_form|cart_form\\/?$",
    "negativepattern": "(sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "TV",
    "pagina": "LP RENT ASSINE CANAISTV",
    "segmento": "RESIDENCIAL",
    "canal": "FORM",
    "origem": "passo221_rentabilizacao"
  },
  {
    "pattern": "^/carrinho.oi.com.br.*cart_all_rentabilizacao.*data_c2c",
    "negativepattern": "chat",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "TV",
    "pagina": "LP RENT AUMENTE_BL",
    "segmento": "RESIDENCIAL",
    "canal": "C2C",
    "origem": "passo221_rentabilizacao"
  },
  {
    "pattern": "^/carrinho.oi.com.br.*cart_all_rentabilizacao.*data_c2c.*chat",
    "negativepattern": "",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "TV",
    "pagina": "LP RENT AUMENTE_BL",
    "segmento": "RESIDENCIAL",
    "canal": "CHAT",
    "origem": "passo221_rentabilizacao"
  },
  {
    "pattern": "^/oilivre\\/?$",
    "negativepattern": "",
    "etapa": "AUDIENCIA",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "PRE-PAGO",
    "pagina": "LP OI LIVRE",
    "segmento": "MOBILIDADE",
    "canal": "",
    "origem": "passo221_rentabilizacao"
  },
  {
    "pattern": "/carrinho.oi.com.br.*/migracao-oi-pre-pago",
    "negativepattern": "(sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "PRE-PAGO",
    "pagina": "LP OI LIVRE",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo221_rentabilizacao"
  },
  {
    "pattern": "^/blackfriday\\/?$",
    "negativepattern": "",
    "etapa": "AUDIENCIA",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP POS-PAGO BLACKFRIDAY",
    "segmento": "MOBILIDADE",
    "canal": "",
    "origem": "passo222_black_Friday"
  },
  {
    "pattern": "(/carrinho.oi.com.br/pos-pago.*lp-pos_pago-black-friday.*central_form/dados-basicos).*",
    "negativepattern": "(sucesso|iniciar|chat-ativo|empresas|moi|\\/ecommerce\\/oi-form|meu-carrinho|cart\\/?$).*",
    "etapa": "CARRINHO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP POS-PAGO BLACKFRIDAY",
    "segmento": "MOBILIDADE",
    "canal": "C2C",
    "origem": "passo222_black_Friday"
  },
  {
    "pattern": "(/carrinho.oi.com.br/pos-pago.*lp-pos_pago-black-friday.*central_form/dados-basicos).*",
    "negativepattern": "(aba|sucesso|landing|c2c|chat|plano|faq|empresas|/mgmtportaloiprd.telemar/|/localhost/|migracao|portabilidade|nova-linha).*",
    "etapa": "CHECKOUT - DADOS BASICOS",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP POS-PAGO BLACKFRIDAY",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo222_black_Friday"
  },
  {
    "pattern": "(/carrinho.oi.com.br/pos-pago.*lp-pos_pago-black-friday.*central_form/forma-ativacao).*",
    "negativepattern": "(dependente|aba|sucesso|landing|c2c|chat|plano|faq|empresas|/mgmtportaloiprd.telemar/|/localhost/|portabilidade|migracao|nova-linha).*",
    "etapa": "CHECKOUT - FORMA ATIVACAO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP POS-PAGO BLACKFRIDAY",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo222_black_Friday"
  },
  {
    "pattern": "(carrinho.oi.com.br/pos-pago/checkout.*lp-pos_pago-black-friday.*/central_form/migracao/token).*",
    "negativepattern": "(dependente|aba|sucesso|landing|c2c|chat|plano|faq|empresas|/mgmtportaloiprd.telemar/|/localhost/|portabilidade|nova-linha).*",
    "etapa": "CHECKOUT - TOKEN/OPERADORA",
    "fluxo": "POS - MIGRACAO",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP POS-PAGO BLACKFRIDAY",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo222_black_Friday"
  },
  {
    "pattern": "(carrinho.oi.com.br/pos-pago/checkout.*lp-pos_pago-black-friday.*/central_form/portabilidade/operadora).*",
    "negativepattern": "(dependente|aba|sucesso|landing|c2c|chat|plano|faq|empresas|/mgmtportaloiprd.telemar/|/localhost/|migracao|nova-linha).*",
    "etapa": "CHECKOUT - TOKEN/OPERADORA",
    "fluxo": "POS - PORTABILIDADE",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP POS-PAGO BLACKFRIDAY",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo222_black_Friday"
  },
  {
    "pattern": "(/carrinho.oi.com.br/pos-pago.*lp-pos_pago-black-friday.*central_form/.*nova-linha.*dados-pessoais).*",
    "negativepattern": "(aba|sucesso|landing|c2c|chat|plano|faq|empresas|/mgmtportaloiprd.telemar/|/localhost/|sucesso|invalido|abandono|incorreto|portabilidade|migracao).*",
    "etapa": "CHECKOUT - DADOS PESSOAIS",
    "fluxo": "POS - NOVA LINHA",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP POS-PAGO BLACKFRIDAY",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo222_black_Friday"
  },
  {
    "pattern": "(/carrinho.oi.com.br/pos-pago.*lp-pos_pago-black-friday.*central_form/.*migracao.*dados-pessoais).*",
    "negativepattern": "(aba|sucesso|landing|c2c|chat|plano|faq|empresas|/mgmtportaloiprd.telemar/|/localhost/|sucesso|invalido|abandono|incorreto|portabilidade|nova-linha).*",
    "etapa": "CHECKOUT - DADOS PESSOAIS",
    "fluxo": "POS - MIGRACAO",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP POS-PAGO BLACKFRIDAY",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo222_black_Friday"
  },
  {
    "pattern": "(/carrinho.oi.com.br/pos-pago.*lp-pos_pago-black-friday.*central_form/.*portabilidade.*dados-pessoais).*",
    "negativepattern": "(aba|sucesso|landing|c2c|chat|plano|faq|empresas|/mgmtportaloiprd.telemar/|/localhost/|sucesso|invalido|abandono|incorreto|migracao|nova-linha).*",
    "etapa": "CHECKOUT - DADOS PESSOAIS",
    "fluxo": "POS - PORTABILIDADE",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP POS-PAGO BLACKFRIDAY",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo222_black_Friday"
  },
  {
    "pattern": "(/carrinho.oi.com.br/pos-pago.*lp-pos_pago-black-friday.*central_form/.*nova-linha/endereco).*",
    "negativepattern": "(aba|sucesso|landing|c2c|chat|plano|faq|empresas|/mgmtportaloiprd.telemar/|/localhost/|sucesso|invalido|abandono|incorreto|portabilidade|migracao).*",
    "etapa": "CHECKOUT - ENDERECO",
    "fluxo": "POS - NOVA LINHA",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP POS-PAGO BLACKFRIDAY",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo222_black_Friday"
  },
  {
    "pattern": "(/carrinho.oi.com.br/pos-pago.*lp-pos_pago-black-friday.*central_form/.*migracao/endereco).*",
    "negativepattern": "(aba|sucesso|landing|c2c|chat|plano|faq|empresas|/mgmtportaloiprd.telemar/|/localhost/|sucesso|invalido|abandono|incorreto|portabilidade|nova-linha).*",
    "etapa": "CHECKOUT - ENDERECO",
    "fluxo": "POS - MIGRACAO",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP POS-PAGO BLACKFRIDAY",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo222_black_Friday"
  },
  {
    "pattern": "(/carrinho.oi.com.br/pos-pago.*lp-pos_pago-black-friday.*central_form/.*portabilidade/endereco).*",
    "negativepattern": "(aba|sucesso|landing|c2c|chat|plano|faq|empresas|/mgmtportaloiprd.telemar/|/localhost/|sucesso|invalido|abandono|incorreto|migracao|nova-linha).*",
    "etapa": "CHECKOUT - ENDERECO",
    "fluxo": "POS - PORTABILIDADE",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP POS-PAGO BLACKFRIDAY",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo222_black_Friday"
  },
  {
    "pattern": "(/carrinho.oi.com.br/pos-pago.*lp-pos_pago-black-friday.*central_form/nova-linha/cobranca).*",
    "negativepattern": "(aba|sucesso|landing|c2c|chat|plano|faq|empresas|/mgmtportaloiprd.telemar/|/localhost/|sucesso|invalido|abandono|incorreto|portabilidade|migracao).*",
    "etapa": "CHECKOUT - COBRANCA",
    "fluxo": "POS - NOVA LINHA",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP POS-PAGO BLACKFRIDAY",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo222_black_Friday"
  },
  {
    "pattern": "(/carrinho.oi.com.br/pos-pago.*lp-pos_pago-black-friday.*central_form/migracao/cobranca).*",
    "negativepattern": "(aba|sucesso|landing|c2c|chat|plano|faq|empresas|/mgmtportaloiprd.telemar/|/localhost/|sucesso|invalido|abandono|incorreto|portabilidade|nova-linha).*",
    "etapa": "CHECKOUT - COBRANCA",
    "fluxo": "POS - MIGRACAO",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP POS-PAGO BLACKFRIDAY",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo222_black_Friday"
  },
  {
    "pattern": "(/carrinho.oi.com.br/pos-pago.*lp-pos_pago-black-friday.*central_form/portabilidade/cobranca).*",
    "negativepattern": "(aba|sucesso|landing|c2c|chat|plano|faq|empresas|/mgmtportaloiprd.telemar/|/localhost/|sucesso|invalido|abandono|incorreto|migracao|nova-linha).*",
    "etapa": "CHECKOUT - COBRANCA",
    "fluxo": "POS - PORTABILIDADE",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP POS-PAGO BLACKFRIDAY",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo222_black_Friday"
  },
  {
    "pattern": "(/carrinho.oi.com.br/pos-pago.*lp-pos_pago-black-friday.*central_form/nova-linha/vencimento).*",
    "negativepattern": "(aba|sucesso|landing|c2c|chat|plano|faq|empresas|/mgmtportaloiprd.telemar/|/localhost/|sucesso|invalido|abandono|incorreto|portabilidade|migracao).*",
    "etapa": "CHECKOUT - VENCIMENTO",
    "fluxo": "POS - NOVA LINHA",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP POS-PAGO BLACKFRIDAY",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo222_black_Friday"
  },
  {
    "pattern": "(/carrinho.oi.com.br/pos-pago.*lp-pos_pago-black-friday.*central_form/migracao/vencimento).*",
    "negativepattern": "(aba|sucesso|landing|c2c|chat|plano|faq|empresas|/mgmtportaloiprd.telemar/|/localhost/|sucesso|invalido|abandono|incorreto|portabilidade|nova-linha).*",
    "etapa": "CHECKOUT - VENCIMENTO",
    "fluxo": "POS - MIGRACAO",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP POS-PAGO BLACKFRIDAY",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo222_black_Friday"
  },
  {
    "pattern": "(/carrinho.oi.com.br/pos-pago.*lp-pos_pago-black-friday.*central_form/portabilidade/vencimento).*",
    "negativepattern": "(aba|sucesso|landing|c2c|chat|plano|faq|empresas|/mgmtportaloiprd.telemar/|/localhost/|sucesso|invalido|abandono|incorreto|migracao|nova-linha).*",
    "etapa": "CHECKOUT - VENCIMENTO",
    "fluxo": "POS - PORTABILIDADE",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP POS-PAGO BLACKFRIDAY",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo222_black_Friday"
  },
  {
    "pattern": "(/carrinho.oi.com.br/pos-pago.*lp-pos_pago-black-friday.*central_form/.*nova-linha/revisar-dados).*",
    "negativepattern": "(aba|sucesso|landing|c2c|chat|plano|faq|empresas|/mgmtportaloiprd.telemar/|/localhost/|sucesso|invalido|abandono|incorreto|portabilidade|migracao).*",
    "etapa": "CHECKOUT - REVISAR DADOS",
    "fluxo": "POS - NOVA LINHA",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP POS-PAGO BLACKFRIDAY",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo222_black_Friday"
  },
  {
    "pattern": "(/carrinho.oi.com.br/pos-pago.*lp-pos_pago-black-friday.*central_form/.*migracao/revisar-dados).*",
    "negativepattern": "(aba|sucesso|landing|c2c|chat|plano|faq|empresas|/mgmtportaloiprd.telemar/|/localhost/|sucesso|invalido|abandono|incorreto|portabilidade|nova-linha).*",
    "etapa": "CHECKOUT - REVISAR DADOS",
    "fluxo": "POS - MIGRACAO",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP POS-PAGO BLACKFRIDAY",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo222_black_Friday"
  },
  {
    "pattern": "(/carrinho.oi.com.br/pos-pago.*lp-pos_pago-black-friday.*central_form/.*portabilidade/revisar-dados).*",
    "negativepattern": "(aba|sucesso|landing|c2c|chat|plano|faq|empresas|/mgmtportaloiprd.telemar/|/localhost/|sucesso|invalido|abandono|incorreto|migracao|nova-linha).*",
    "etapa": "CHECKOUT - REVISAR DADOS",
    "fluxo": "POS - PORTABILIDADE",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP POS-PAGO BLACKFRIDAY",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo222_black_Friday"
  },
  {
    "pattern": "(carrinho.oi.com.br/pos-pago.*lp-pos_pago-black-friday.*central_form.*nova-linha\\/sucesso).*",
    "negativepattern": "(portabilidade|migracao).*",
    "etapa": "CARRINHO - SUCESSO",
    "fluxo": "POS - NOVA LINHA",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP POS-PAGO BLACKFRIDAY",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo222_black_Friday"
  },
  {
    "pattern": "(carrinho.oi.com.br/pos-pago.*lp-pos_pago-black-friday.*central_form.*migracao\\/sucesso).*",
    "negativepattern": "(portabilidade|nova-linha).*",
    "etapa": "CARRINHO - SUCESSO",
    "fluxo": "POS - MIGRACAO",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP POS-PAGO BLACKFRIDAY",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo222_black_Friday"
  },
  {
    "pattern": "(carrinho.oi.com.br/pos-pago.*lp-pos_pago-black-friday.*central_form.*portabilidade\\/sucesso).*",
    "negativepattern": "(migracao|nova-linha).*",
    "etapa": "CARRINHO - SUCESSO",
    "fluxo": "POS - PORTABILIDADE",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP POS-PAGO BLACKFRIDAY",
    "segmento": "MOBILIDADE",
    "canal": "FORM",
    "origem": "passo222_black_Friday"
  },
  {
    "pattern": "^/static/assine-pos-a\\/?$",
    "negativepattern": "(ofertas|aba|sucesso|c2c|chat|form|plano|faq).*",
    "etapa": "AUDIENCIA",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP ASSINE POS A",
    "segmento": "MOBILIDADE",
    "canal": "",
    "origem": "passo244_lp_assine_pos_a"
  },
  {
    "pattern": "carrinho.oi.com.br/lp_assine-pos-static-occ.*central_c2c.*sucesso_op",
    "negativepattern": "",
    "etapa": "CARRINHO - SUCESSO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP ASSINE POS A",
    "segmento": "MOBILIDADE",
    "canal": "",
    "origem": "passo244_lp_assine_pos_a"
  },
  {
    "pattern": "^/carrinho.oi.com.br/pos-pago/(celular-pos-pago|indefinido).*sub-menu_ajuda.*central_c2c",
    "negativepattern": "lp-pos_pago-black-friday|dados|dependentes|sucesso|endereco|cobranca|revisar|ativacao|abandono",
    "etapa": "AUDIENCIA",
    "fluxo": "",
    "tipo": "PAGINA",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO OCC",
    "segmento": "MOBILIDADE",
    "canal": "C2C",
    "origem": "passo233_c2c_occ"
  },
  {
    "pattern": "^/carrinho.oi.com.br/pos-pago/(celular-pos-pago|indefinido).*sub-menu_ajuda.*central_c2c.*sucesso_op",
    "negativepattern": "lp-pos_pago-black-friday",
    "etapa": "AUDIENCIA - SUCESSO",
    "fluxo": "",
    "tipo": "PAGINA",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO OCC",
    "segmento": "MOBILIDADE",
    "canal": "C2C",
    "origem": "passo233_c2c_occ"
  },
  {
    "pattern": "carrinho.oi.com.br/pos-pago.*detalhes-da-oferta.*sub-menu_ajuda.*central_c2c",
    "negativepattern": "ccstore|lp-pos_pago-black-friday|dados|dependentes|sucesso|endereco|cobranca|revisar|ativacao|abandono",
    "etapa": "DETALHE DA OFERTA",
    "fluxo": "",
    "tipo": "PAGINA",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO OCC",
    "segmento": "MOBILIDADE",
    "canal": "C2C",
    "origem": "passo233_c2c_occ"
  },
  {
    "pattern": "carrinho.oi.com.br/pos-pago.*detalhes-da-oferta.*central_c2c.*sucesso_op",
    "negativepattern": "ccstore|lp-pos_pago-black-friday|dados|dependentes|endereco|cobranca|revisar|ativacao|abandono",
    "etapa": "DETALHE DA OFERTA - SUCESSO",
    "fluxo": "",
    "tipo": "PAGINA",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO OCC",
    "segmento": "MOBILIDADE",
    "canal": "C2C",
    "origem": "passo233_c2c_occ"
  },
  {
    "pattern": "^/carrinho.oi.com.br/pos-pago.*checkout.*central_c2c.*dados-basicos",
    "negativepattern": "ccstore|lp-pos_pago-black-friday|sucesso|dependente|abandono|invalido|incorreto",
    "etapa": "CHECKOUT - DADOS BASICOS",
    "fluxo": "",
    "tipo": "PAGINA",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO OCC",
    "segmento": "MOBILIDADE",
    "canal": "C2C",
    "origem": "passo233_c2c_occ"
  },
  {
    "pattern": "^/carrinho.oi.com.br/pos-pago.*checkout.*central_c2c/dados-basicos.*sucesso_op",
    "negativepattern": "ccstore|lp-pos_pago-black-friday|dependente|abandono|invalido|incorreto",
    "etapa": "CHECKOUT - DADOS BASICOS SUCESSO",
    "fluxo": "",
    "tipo": "PAGINA",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO OCC",
    "segmento": "MOBILIDADE",
    "canal": "C2C",
    "origem": "passo233_c2c_occ"
  },
  {
    "pattern": "^/carrinho.oi.com.br/pos-pago.*checkout.*central_c2c/forma-ativacao",
    "negativepattern": "ccstore|lp-pos_pago-black-friday|sucesso|dependente|abandono|incorreto|invalido",
    "etapa": "CHECKOUT - FORMA ATIVACAO",
    "fluxo": "",
    "tipo": "PAGINA",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO OCC",
    "segmento": "MOBILIDADE",
    "canal": "C2C",
    "origem": "passo233_c2c_occ"
  },
  {
    "pattern": "^/carrinho.oi.com.br/pos-pago.*checkout.*central_c2c/forma-ativacao.*sucesso_op",
    "negativepattern": "ccstore|lp-pos_pago-black-friday|dependente|abandono|incorreto|invalido",
    "etapa": "CHECKOUT - FORMA ATIVACAO SUCESSO",
    "fluxo": "",
    "tipo": "PAGINA",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO OCC",
    "segmento": "MOBILIDADE",
    "canal": "C2C",
    "origem": "passo233_c2c_occ"
  },
  {
    "pattern": "^/carrinho.oi.com.br/pos-pago/checkout/.*central_c2c/(portabilidade|migracao)/forma-ativacao$",
    "negativepattern": "ccstore|lp-pos_pago-black-friday|incorretos|sucesso|abandono|invalido",
    "etapa": "CHECKOUT - TOKEN/OPERADORA",
    "fluxo": "",
    "tipo": "PAGINA",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO OCC",
    "segmento": "MOBILIDADE",
    "canal": "C2C",
    "origem": "passo233_c2c_occ"
  },
  {
    "pattern": "^/carrinho.oi.com.br/pos-pago.*checkout.*central_c2c.*(migracao|portabilidade).*sucesso_op",
    "negativepattern": "ccstore|lp-pos_pago-black-friday|incorretos|abandono|invalido",
    "etapa": "CHECKOUT - TOKEN/OPERADORA SUCESSO",
    "fluxo": "",
    "tipo": "PAGINA",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO OCC",
    "segmento": "MOBILIDADE",
    "canal": "C2C",
    "origem": "passo233_c2c_occ"
  },
  {
    "pattern": "^/carrinho.oi.com.br/pos-pago.*central_c2c.*dados-pessoais",
    "negativepattern": "ccstore|lp-pos_pago-black-friday|sucesso|abandono",
    "etapa": "CHECKOUT - DADOS PESSOAIS",
    "fluxo": "",
    "tipo": "PAGINA",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO OCC",
    "segmento": "MOBILIDADE",
    "canal": "C2C",
    "origem": "passo233_c2c_occ"
  },
  {
    "pattern": "^/carrinho.oi.com.br/pos-pago.*central_c2c.*dados-pessoais.*sucesso_op",
    "negativepattern": "ccstore|lp-pos_pago-black-friday|abandono",
    "etapa": "CHECKOUT - DADOS PESSOAIS SUCESSO",
    "fluxo": "",
    "tipo": "PAGINA",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO OCC",
    "segmento": "MOBILIDADE",
    "canal": "C2C",
    "origem": "passo233_c2c_occ"
  },
  {
    "pattern": "^/carrinho.oi.com.br/pos-pago.*central_c2c.*endereco",
    "negativepattern": "ccstore|lp-pos_pago-black-friday|sucesso|abandono",
    "etapa": "CHECKOUT - ENDERECO",
    "fluxo": "",
    "tipo": "PAGINA",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO OCC",
    "segmento": "MOBILIDADE",
    "canal": "C2C",
    "origem": "passo233_c2c_occ"
  },
  {
    "pattern": "^/carrinho.oi.com.br/pos-pago.*central_c2c.*endereco.*sucesso_op",
    "negativepattern": "ccstore|lp-pos_pago-black-friday|abandono",
    "etapa": "CHECKOUT - ENDERECO SUCESSO",
    "fluxo": "",
    "tipo": "PAGINA",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO OCC",
    "segmento": "MOBILIDADE",
    "canal": "C2C",
    "origem": "passo233_c2c_occ"
  },
  {
    "pattern": "^/carrinho.oi.com.br/pos-pago.*central_c2c.*revisar-dados",
    "negativepattern": "ccstore|lp-pos_pago-black-friday|sucesso|abandono",
    "etapa": "CHECKOUT - REVISAR DADOS",
    "fluxo": "",
    "tipo": "PAGINA",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO OCC",
    "segmento": "MOBILIDADE",
    "canal": "C2C",
    "origem": "passo233_c2c_occ"
  },
  {
    "pattern": "^/carrinho.oi.com.br/pos-pago.*central_c2c.*revisar-dados.*sucesso_op",
    "negativepattern": "ccstore|lp-pos_pago-black-friday|abandono",
    "etapa": "CHECKOUT - REVISAR DADOS SUCESSO",
    "fluxo": "",
    "tipo": "PAGINA",
    "produto": "POS-PAGO",
    "pagina": "P POS-PAGO OCC",
    "segmento": "MOBILIDADE",
    "canal": "C2C",
    "origem": "passo233_c2c_occ"
  },
  {
    "pattern": "carrinho.oi.com.br/pos-pago.*detalhes-da-oferta.*lp-pos_pago-black-friday.*sub-menu_ajuda.*central_c2c",
    "negativepattern": "ccstore|dados|dependentes|sucesso|endereco|cobranca|revisar|ativacao|abandono",
    "etapa": "DETALHE DA OFERTA",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP POS-PAGO BLACKFRIDAY",
    "segmento": "MOBILIDADE",
    "canal": "C2C",
    "origem": "passo233_c2c_occ"
  },
  {
    "pattern": "carrinho.oi.com.br/pos-pago.*detalhes-da-oferta.*lp-pos_pago-black-friday.*central_c2c.*sucesso_op",
    "negativepattern": "ccstore|dados|dependentes|endereco|cobranca|revisar|ativacao|abandono",
    "etapa": "DETALHE DA OFERTA - SUCESSO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP POS-PAGO BLACKFRIDAY",
    "segmento": "MOBILIDADE",
    "canal": "C2C",
    "origem": "passo233_c2c_occ"
  },
  {
    "pattern": "^/carrinho.oi.com.br/pos-pago.*checkout.*lp-pos_pago-black-friday.*central_c2c.*dados-basicos",
    "negativepattern": "ccstore|sucesso|dependente|abandono|invalido|incorreto",
    "etapa": "CHECKOUT - DADOS BASICOS",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP POS-PAGO BLACKFRIDAY",
    "segmento": "MOBILIDADE",
    "canal": "C2C",
    "origem": "passo233_c2c_occ"
  },
  {
    "pattern": "^/carrinho.oi.com.br/pos-pago.*checkout.*lp-pos_pago-black-friday.*central_c2c/dados-basicos.*sucesso_op",
    "negativepattern": "ccstore|dependente|abandono|invalido|incorreto",
    "etapa": "CHECKOUT - DADOS BASICOS SUCESSO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP POS-PAGO BLACKFRIDAY",
    "segmento": "MOBILIDADE",
    "canal": "C2C",
    "origem": "passo233_c2c_occ"
  },
  {
    "pattern": "^/carrinho.oi.com.br/pos-pago.*checkout.*lp-pos_pago-black-friday.*central_c2c/forma-ativacao",
    "negativepattern": "ccstore|sucesso|dependente|abandono|incorreto|invalido",
    "etapa": "CHECKOUT - FORMA ATIVACAO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP POS-PAGO BLACKFRIDAY",
    "segmento": "MOBILIDADE",
    "canal": "C2C",
    "origem": "passo233_c2c_occ"
  },
  {
    "pattern": "^/carrinho.oi.com.br/pos-pago.*checkout.*lp-pos_pago-black-friday.*central_c2c/forma-ativacao.*sucesso_op",
    "negativepattern": "ccstore|dependente|abandono|incorreto|invalido",
    "etapa": "CHECKOUT - FORMA ATIVACAO SUCESSO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP POS-PAGO BLACKFRIDAY",
    "segmento": "MOBILIDADE",
    "canal": "C2C",
    "origem": "passo233_c2c_occ"
  },
  {
    "pattern": "^/carrinho.oi.com.br/pos-pago/checkout/.*lp-pos_pago-black-friday.*central_c2c/(portabilidade|migracao)/forma-ativacao$",
    "negativepattern": "ccstore|incorretos|sucesso|abandono|invalido",
    "etapa": "CHECKOUT - TOKEN/OPERADORA",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP POS-PAGO BLACKFRIDAY",
    "segmento": "MOBILIDADE",
    "canal": "C2C",
    "origem": "passo233_c2c_occ"
  },
  {
    "pattern": "^/carrinho.oi.com.br/pos-pago.*checkout.*lp-pos_pago-black-friday.*central_c2c.*(migracao|portabilidade).*sucesso_op",
    "negativepattern": "ccstore|incorretos|abandono|invalido",
    "etapa": "CHECKOUT - TOKEN/OPERADORA SUCESSO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP POS-PAGO BLACKFRIDAY",
    "segmento": "MOBILIDADE",
    "canal": "C2C",
    "origem": "passo233_c2c_occ"
  },
  {
    "pattern": "^/carrinho.oi.com.br/pos-pago.*lp-pos_pago-black-friday.*central_c2c.*dados-pessoais",
    "negativepattern": "ccstore|sucesso|abandono",
    "etapa": "CHECKOUT - DADOS PESSOAIS",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP POS-PAGO BLACKFRIDAY",
    "segmento": "MOBILIDADE",
    "canal": "C2C",
    "origem": "passo233_c2c_occ"
  },
  {
    "pattern": "^/carrinho.oi.com.br/pos-pago.*lp-pos_pago-black-friday.*central_c2c.*dados-pessoais.*sucesso_op",
    "negativepattern": "ccstore|abandono",
    "etapa": "CHECKOUT - DADOS PESSOAIS SUCESSO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP POS-PAGO BLACKFRIDAY",
    "segmento": "MOBILIDADE",
    "canal": "C2C",
    "origem": "passo233_c2c_occ"
  },
  {
    "pattern": "^/carrinho.oi.com.br/pos-pago.*lp-pos_pago-black-friday.*central_c2c.*endereco",
    "negativepattern": "ccstore|sucesso|abandono",
    "etapa": "CHECKOUT - ENDERECO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP POS-PAGO BLACKFRIDAY",
    "segmento": "MOBILIDADE",
    "canal": "C2C",
    "origem": "passo233_c2c_occ"
  },
  {
    "pattern": "^/carrinho.oi.com.br/pos-pago.*lp-pos_pago-black-friday.*central_c2c.*endereco.*sucesso_op",
    "negativepattern": "ccstore|abandono",
    "etapa": "CHECKOUT - ENDERECO SUCESSO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP POS-PAGO BLACKFRIDAY",
    "segmento": "MOBILIDADE",
    "canal": "C2C",
    "origem": "passo233_c2c_occ"
  },
  {
    "pattern": "^/carrinho.oi.com.br/pos-pago.*lp-pos_pago-black-friday.*central_c2c.*revisar-dados",
    "negativepattern": "ccstore|sucesso|abandono",
    "etapa": "CHECKOUT - REVISAR DADOS",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP POS-PAGO BLACKFRIDAY",
    "segmento": "MOBILIDADE",
    "canal": "C2C",
    "origem": "passo233_c2c_occ"
  },
  {
    "pattern": "^/carrinho.oi.com.br/pos-pago.*lp-pos_pago-black-friday.*central_c2c.*revisar-dados.*sucesso_op",
    "negativepattern": "ccstore|abandono",
    "etapa": "CHECKOUT - REVISAR DADOS SUCESSO",
    "fluxo": "",
    "tipo": "LANDING",
    "produto": "POS-PAGO",
    "pagina": "LP POS-PAGO BLACKFRIDAY",
    "segmento": "MOBILIDADE",
    "canal": "C2C",
    "origem": "passo233_c2c_occ"
  }
 ]